### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by kirill0ermakov** [tsukumijima/Real-ESRGAN-GUI#1]
Hello! English version, maybe create in future?

**Comment by tsukumijima** [comment]
There are no plans to create an English version at this time. Do you need one?

**Comment by kirill0ermakov** [comment]
I don't know Japanese, so yes, I could help with the translation file. I would also, of course, like to help and create a translation in my native language, Ukrainian.

**Comment by 233lol** [comment]
> There are no plans to create an English version at this time. Do you need one?

I can translate into Chinese.

**Comment by tsukumijima** [comment]
https://github.com/tsukumijima/Real-ESRGAN-GUI/pull/2
Merged pull requests add localization support and translations for English and Ukrainian.
For Chinese, just send me a pull request for the translation data and we will merge it in as well.
