### ISSUE TITLE
Chinese translation document

### ISSUE THREAD

**Issue by ghost** [tsukumijima/Real-ESRGAN-GUI#5]
[zh-CN.zip](https://github.com/tsukumijima/Real-ESRGAN-GUI/files/9665575/zh-CN.zip)
Translated by myself,
Can you add it to your software？

**Comment by tsukumijima** [comment]
I have already received the Chinese translation (#4) from someone else and have merged it.
I don't understand Chinese, so if there is anything unnatural in the translation, please report it to me and I will fix it.
