### ISSUE TITLE
Can you add waifu2x-ncnn-vulkan to the software

### ISSUE THREAD

**Issue by ghost** [tsukumijima/Real-ESRGAN-GUI#6]
Make an All-in-One software
Sometimes waifu2x works better

**Comment by tsukumijima** [comment]
By design, it is possible to add other xxxx-ncnn-vulkan GUI wrappers.
However, since Real-ESRGAN and Real-CUGAN are superior to waifu2x, I don't plan to add waifu2x-ncnn-vulkan.
I may add realsr-ncnn-vulkan, but there is no motivation...
