### ISSUE TITLE
保存形式で JPEG を選択しても PNG で出力される

### ISSUE THREAD

**Issue by kmtr0724** [tsukumijima/Real-ESRGAN-GUI#7]

**Comment by kmtr0724** [comment]
ver1.2.0にて、保存形式でJPEGを選択してもPNGで出力されます。
ファイル名も「hogehoge.jpg.png」と拡張子がくっついた状態になります。

**Comment by tsukumijima** [comment]
バックエンドで使っている realesrgan-ncnn-vulkan の仕様上、フォルダ選択からの一括実行の場合はそうした挙動になってしまうようです（正直なぜそのような挙動になるのか掴めておらず、修正する気力もないのでそのままにしていました…）。
ファイル選択で拡大したときは問題ないと思いますので、そちらでお試しいただければ…。

**Comment by kmtr0724** [comment]
理解しました。ありがとうございます
