### ISSUE TITLE
Occasionally Real-CUGAN generates corrupted images

### ISSUE THREAD

**Issue by yife** [tsukumijima/Real-ESRGAN-GUI#8]
### Issue description
Real-CUGANに特定の画像を与えると、崩壊した画像が生成されます。

Real-ESRGAN-GUI ver1.2.0にて確認。
Real-CUGAN / models-pro / ノイズを除去しない / 2倍の解像度に拡大。
保存形式 jpegおよびpngの両方にて症状が発生。

### What's the expected result?
正常に拡大された画像が出力される。

### What's the actual result?
ネガポジ反転したような、奇妙に粗い画像が出力される。

### Additional details / screenshot

- [入力画像](https://imgur.com/a/qOkZWlh)
- [出力された画像](https://imgur.com/a/JKgF1d2)

入力画像のSHA1 Hash
- 34710118121fd17aefc0ea8b2cae116ab89a5cdd
- 0cea93272c094de3473969c80f59cd3ff9c2a9ec

**Comment by tsukumijima** [comment]
Real-ESRGAN-GUI は Readme にある通り、realesrgan-ncnn-vulkan / realcugan-ncnn-vulkan の GUI ラッパーです。画像の生成処理には一切手を加えていないので、これは realcugan-ncnn-vulkan の不具合ということになると思います。
私は残念ながら realcugan-ncnn-vulkan の動作原理は理解できていませんし、私の技術力では直すのも難しいです…。
realcugan-ncnn-vulkan 本家のリポジトリであれば、もしかすると取り合ってくれるかもしれません。
