### ISSUE TITLE
フォルダの画像を一括変換した際に凄まじく遅い

### ISSUE THREAD

**Issue by rodigh** [tsukumijima/Real-ESRGAN-GUI#9]
例として私の環境でフォルダを指定し、100ファイル処理した場合に約100秒かかります。
realcugan-ncnn-vulkan.exeをコマンドプロンプトで実行し、同じフォルダを処理すると10秒程度で完了します。

上記2つについては完全に一致するかは分かりませんが引数などは同じと思われる条件でやっています。

また、利用モデルなどが起動のたびにデフォルトに戻ってしまうため、設定が保存できればなお便利かと思っています。

**Comment by tsukumijima** [comment]
> 例として私の環境でフォルダを指定し、100ファイル処理した場合に約100秒かかります。
realcugan-ncnn-vulkan.exeをコマンドプロンプトで実行し、同じフォルダを処理すると10秒程度で完了します。

正直私がそこまでハードな使い方をしていないのであれなのですが（私はせいぜい数ファイル程度の画像しか拡大することがない）、おそらく実装方法の違いにあると思っています。
realesrgan-ncnn-vulkan や realcugan-ncnn-vulkan にはフォルダを直接指定して一括で拡大処理して出力先フォルダに出力するオプション引数があるようですが、実は開発当時はその機能を知りませんでした。それもあって、入力元にフォルダを指定した場合も、内部的には1ファイルごとにコマンドを実行する実装になってしまっています。
そのあたりで効率の差が出てしまっているのかもしれません。

> 利用モデルなどが起動のたびにデフォルトに戻ってしまうため、設定が保存できればなお便利かと思っています。

いろいろ改善したい部分は多々あるのですが、私自身がそこまでハードに使っているわけではないこと（自分自身のニーズはすでに満たせている）、あまり Real-ESRGAN-GUI の開発に割けるリソースがないこともあって、しばらくそのままになってしまっています…。

**Comment by rodigh** [comment]
了解しました、ありがとうございます。
設定の保存機能はともかくとしてフォルダ変換について本家の機能より圧倒的に劣っている状況は元の製作者様にあまりに失礼だと思います。
